# Generated by Django 3.2.11 on 2022-05-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egresados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('fech_naci', models.DateField()),
                ('carrera', models.CharField(choices=[('IBQ', 'Ingeniería Bioquimica'), ('IEN', 'Ingeniería Electrónica'), ('IE', 'Ingeniería Eléctrica'), ('II', 'Ingeniería Industrial'), ('IMT', 'Ingeniería Mecatrónica'), ('IM', 'Ingeniería Mecánica'), ('IGE', 'Ingeniería en Gestión Empresarial'), ('IMR', 'Ingeniería en Materiales'), ('ISC', 'Ingeniería en Sistemas Computacionales'), ('ITIC', 'Ingeniería en Tecnologias de la Informacion y Comunicaciones'), ('CP', 'Contador Público'), ('A', 'Administración')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
