# Generated by Django 4.0.3 on 2022-05-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGPS', '0002_alter_usuarios_email_profesional_personales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='empleo_previo',
        ),
        migrations.CreateModel(
            name='Profesionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleo_previo', models.CharField(max_length=50)),
                ('id_em', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoGPS.profesional')),
            ],
        ),
    ]
