# Generated by Django 4.0.3 on 2022-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGPS', '0003_remove_profesional_empleo_previo_profesionale'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='empleo_previ',
            field=models.CharField(default='ninguno', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profesionale',
        ),
    ]
