# Generated by Django 3.2.11 on 2022-05-24 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoGPS', '0004_profesional_empleo_previ_delete_profesionale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresados',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
