# Generated by Django 3.2.11 on 2022-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGPS', '0006_auto_20220524_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
