# Generated by Django 3.2.11 on 2022-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGPS', '0007_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresados',
            name='fech_naci',
            field=models.DateField(null=True),
        ),
    ]
