# Generated by Django 3.2.11 on 2022-05-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoGPS', '0008_alter_egresados_fech_naci'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresados',
            options={},
        ),
        migrations.AlterModelManagers(
            name='egresados',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='password',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='egresados',
            name='username',
        ),
        migrations.AddField(
            model_name='egresados',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
